### PR TITLE
DK and I finished the pandas file

### PR DESCRIPTION
**Pull request by EricR401S**
@Yer1k would you please review this?

### CODE REVIEW

**Comment by Yer1k** [comment]
Hey @EricR401S, nice job, let's merge it!

**Review by Yer1k — CHANGES_REQUESTED** [review]
Could you please delete 3+3 at line 2 before we merge it to main branch, thanks. @EricR401S

**Comment by EricR401S** [comment]
I tweaked it

**Comment by EricR401S** [comment]
I tweaked it @Yer1k

**Pull request merged**
